parameters:
  agentOs: ''
  queue: {}
  variables: {}

phases:
- template: /eng/common/templates/phases/base.yml
  parameters:
    name: ${{ parameters.agentOs }}
    enableTelemetry: true
    enableMicrobuild: true
    publicBuildReasons: PullRequest
    queue: ${{ parameters.queue }}
    variables: 
      ${{ insert }}: ${{ parameters.variables }}
      _HelixType: build/product
      _HelixBuildConfig: $(_BuildConfig)
      _TeamName: DotNetCore
      ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
        _HelixSource: pr/dotnet/sdk/$(Build.SourceBranch)
        _OfficialBuildIdArgs: ''
        _PublishArgs: ''
        _SignArgs: ''
      ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
        _HelixSource: official/dotnet/sdk/$(Build.SourceBranch)
        _OfficialBuildIdArgs: /p:OfficialBuildId=$(BUILD.BUILDNUMBER)
        _PublishArgs: /p:DotNetPublishBlobFeedKey=$(dotnetfeed-storage-access-key-1)
                  /p:DotNetPublishBlobFeedUrl=$(PB_PublishBlobFeedUrl)
                  /p:DotNetPublishToBlobFeed=$(_DotNetPublishToBlobFeed)
                  /p:DotNetSymbolServerTokenMsdl=$(microsoft-symbol-server-pat)
                  /p:DotNetSymbolServerTokenSymWeb=$(symweb-symbol-server-pat)
                  /p:PB_PublishType=$(_PublishType)
        _SignArgs: /p:DotNetSignType=$(_SignType) /p:TeamName=$(_TeamName)

    steps:
    - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
      - task: AzureKeyVault@1
        inputs:
          azureSubscription: 'DotNet-Engineering-Services_KeyVault'
          KeyVaultName: EngKeyVault
          SecretsFilter: 'dotnetfeed-storage-access-key-1,microsoft-symbol-server-pat,symweb-symbol-server-pat'
        condition: succeeded()
      - task: AzureKeyVault@1
        inputs:
          azureSubscription: 'HelixProd_KeyVault'
          KeyVaultName: HelixProdKV
          SecretsFilter: 'HelixApiAccessToken'
        condition: always()

    - ${{ if eq(parameters.agentOs, 'Windows_NT') }}:
      - script: eng\common\CIBuild.cmd
                  -configuration %BuildConfig%
                  $(_PublishArgs)
                  $(_SignArgs)
                  $(_OfficialBuildIdArgs)
        displayName: Build
        env:
          BuildConfig: $(_BuildConfig)
          BlobFeedUrl: $(PB_PublishBlobFeedUrl)
          PublishType: $(_PublishType)

    - ${{ if eq(parameters.agentOs, 'Windows_NT_FullFramework') }}:
      - script: eng\common\CIBuild.cmd 
                  -configuration %BuildConfig%
                  -fullMSBuild
                  $(_PublishArgs)
                  $(_SignArgs)
                  $(_OfficialBuildIdArgs)
        displayName: Build
        env:
          BuildConfig: $(_BuildConfig)
          BlobFeedUrl: $(PB_PublishBlobFeedUrl)
          PublishType: $(_PublishType)

    - ${{ if notIn(parameters.agentOs, 'Windows_NT', 'Windows_NT_FullFramework') }}:
      - script: eng/common/cibuild.sh 
                  --configuration $BuildConfig
                  $(_PublishArgs)
                  $(_SignArgs)
                  $(_OfficialBuildIdArgs)
        displayName: Build
        env:
          BuildConfig: $(_BuildConfig)
          BlobFeedUrl: $(PB_PublishBlobFeedUrl)
          PublishType: $(_PublishType)

    - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
      - task: PublishTestResults@1
        displayName: Publish Test Results
        inputs:
          testRunner: XUnit
          testResultsFiles: 'artifacts/TestResults/$(_BuildConfig)/*.xml'
          testRunTitle: 'Unit Test Results'
          platform: '$(BuildPlatform)'
          configuration: '$(_BuildConfig)'
        condition: and(succeededOrFailed(), ne(variables['PB_SkipTests'], 'true'))

      - task: CopyFiles@2
        displayName: Stage Build Artifacts
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)'
          Contents: |
           artifacts\bin\$(_BuildConfig)\**\*
           artifacts\log\$(_BuildConfig)\**\*
           artifacts\packages\$(_BuildConfig)\**\*
           artifacts\TestResults\$(_BuildConfig)\**\*
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
        condition: and(succeededOrFailed(), in(variables['_PublishType'], 'drop', 'blob'))

      - task: PublishBuildArtifacts@1
        displayName: Publish Build Artifacts
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)\artifacts'
          ArtifactName: '$(Build.BuildNumber)'
          publishLocation: FilePath
          TargetPath: '$(DropRoot)\$(TeamName)\$(Build.DefinitionName)'
        condition: and(succeededOrFailed(), in(variables['_PublishType'], 'drop', 'blob'))
